apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: advanced-deployment
  template:
    metadata:
      labels:
        name: advanced-deployment
    spec:
      serviceAccountName: advanced-deployment
      containers:
        - name: advanced-deployment
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - advanced-deployment
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "advanced-deployment"
